// GENERATED by tools/make-sw.mjs — do not edit.  Re-run it after adding an
// asset; the list below is what an offline reload has to find in the cache
// (`FYL-DESIGN-18` U-20).
//
// ★Cache-first for everything in the list, network-only for `/api/`.  A
// desktop viewer's data face must never be answered out of a cache: 「网关未连」
// cached once would outlive the gateway coming up.
// ★One cache per app version.  The page and the wasm are one build; serving a
// new page against an old module is the failure this naming prevents, and
// activate() drops every cache that is not this one.
const VERSION = "0.0.1-alpha";
const CACHE = 'fylite-' + VERSION;
const PRECACHE = [
  "assets/abi.json",
  "assets/appio.js",
  "assets/bundle.js",
  "assets/casereport.js",
  "assets/checkpoint.js",
  "assets/deck-names.js",
  "assets/device.js",
  "assets/devices.js",
  "assets/edit.js",
  "assets/factsdb.js",
  "assets/fig.js",
  "assets/flag-en.svg",
  "assets/flag-zh.svg",
  "assets/form.js",
  "assets/fy_mark.svg",
  "assets/fylite.js",
  "assets/fylite_kernel_ext.wasm.0.0.1",
  "assets/fylite_logo.svg",
  "assets/fylite_rs.wasm.0.0.1",
  "assets/fylite_web.wasm.0.0.1",
  "assets/fyo-interface.js",
  "assets/fyo.js",
  "assets/fyodev.js",
  "assets/geqdsk.js",
  "assets/h5source.js",
  "assets/handoff.js",
  "assets/host.js",
  "assets/i18n.js",
  "assets/kernel-abi.js",
  "assets/kernelapi.js",
  "assets/lang-breakdown-en.js",
  "assets/lang-breakdown-zh.js",
  "assets/lang-credits-en.js",
  "assets/lang-credits-zh.js",
  "assets/lang-design-en.js",
  "assets/lang-design-zh.js",
  "assets/lang-en.js",
  "assets/lang-evolve-en.js",
  "assets/lang-evolve-zh.js",
  "assets/lang-features-en.js",
  "assets/lang-features-zh.js",
  "assets/lang-home-en.js",
  "assets/lang-home-zh.js",
  "assets/lang-interp-en.js",
  "assets/lang-interp-zh.js",
  "assets/lang-mds-en.js",
  "assets/lang-mds-zh.js",
  "assets/lang-model-en.js",
  "assets/lang-model-zh.js",
  "assets/lang-pd-en.js",
  "assets/lang-pd-zh.js",
  "assets/lang-pulse-en.js",
  "assets/lang-pulse-zh.js",
  "assets/lang-report-en.js",
  "assets/lang-report-zh.js",
  "assets/lang-sim-en.js",
  "assets/lang-sim-zh.js",
  "assets/lang-site-en.js",
  "assets/lang-site-zh.js",
  "assets/lang-transport-en.js",
  "assets/lang-transport-zh.js",
  "assets/lang-zerod-en.js",
  "assets/lang-zerod-zh.js",
  "assets/lang-zh.js",
  "assets/mds-bind.json",
  "assets/mds-catalog.js",
  "assets/mds-request.js",
  "assets/mds-source.js",
  "assets/mdsplus.js",
  "assets/plot.js",
  "assets/qr-site.svg",
  "assets/report-page.js",
  "assets/run.js",
  "assets/runtime-version.js",
  "assets/runtimeweb.js",
  "assets/scenario-analysis.js",
  "assets/scenario-model.js",
  "assets/scenario-pulse_design.js",
  "assets/scenario.js",
  "assets/session.js",
  "assets/shell.css",
  "assets/shell.js",
  "assets/site.css",
  "assets/site.js",
  "assets/sources.js",
  "assets/style.css",
  "assets/theme.js",
  "assets/version.js",
  "assets/vocab-model.js",
  "assets/workbench.js",
  "assets/worker.js",
  "credits.en.html",
  "credits.html",
  "features.en.html",
  "features.html",
  "index.en.html",
  "index.html",
  "pages/analysis.html",
  "pages/data.html",
  "pages/model.html",
  "pages/page_analysis.html",
  "pages/page_data.html",
  "pages/page_model.html",
  "pages/page_pulse_design.html",
  "pages/page_report.html",
  "pages/pulse_design.html",
  "pages/report.html"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) =>
    //: ★one at a time, and a miss does not fail the install.  `addAll` is
    //: all-or-nothing: one asset that 404s (a wasm that this checkout does not
    //: carry) would leave the site with NO cache at all rather than a partial
    //: one, and the reader would discover it only offline.
    Promise.all(PRECACHE.map((u) => c.add(u).catch(() => null)))
  ).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (url.pathname.indexOf('/api/') >= 0) return;          // the live data face
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) =>
    hit || fetch(e.request).then((res) => {
      //: what was fetched and is ours joins the cache, so a page reached by a
      //: link nobody precached is there next time too
      if (res && res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(e.request, copy));
      }
      return res;
    }).catch(() => hit))
  );
});
